## Append samples of your project ##
resources:
- proxmox_v1alpha1_virtualmachine.yaml
- proxmox_v1alpha1_managedvirtualmachine.yaml
- proxmox_v1alpha1_virtualmachineset.yaml
- proxmox_v1alpha1_virtualmachinesnapshot.yaml
- proxmox_v1alpha1_virtualmachinesnapshotpolicy.yaml
- proxmox_v1alpha1_container.yaml
- proxmox_v1alpha1_storagedownloadurl.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
