apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineSnapshot
metadata:
  labels:
    app.kubernetes.io/name: virtualmachinesnapshot
    app.kubernetes.io/instance: virtualmachinesnapshot-sample
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubemox
  name: virtualmachinesnapshot-sample
spec:
  virtualMachineName: "virtualmachine-sample-clone"
  snapshotName: "test-snapshot"